import Head from 'next/head'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Whats App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
    </div>
  )
}

const Header = () => {
  return (
    <div className='flex flex-1 bg-sky-500 w-full h-30'>Hello World</div>
  )
}
